### ISSUE TITLE
List of Azure Services

### ISSUE THREAD

**Issue by FlippieCoetser** [Royal-Philips/iDiscover#2]
A list of Azure Services is required for Philips IT to proceed with the opening of account.

**Comment by Malyngo** [comment]
Only a single one:
* **Azure Active Directory** for sign in. Basic is enough for functionality, but Premium is required for the customized login screen.

One of each of the below for each environment. So one for production, one for QA. I'd probably like to keep Dev on continuum side, so I can easily tear stuff down there and update it.
* **Azure Cloud Service** (x envirionment)
* **SQL Azure Database** (x environment)

**Comment by FlippieCoetser** [comment]
is `iDiscover.API` and `iDiscover.APP` supported and hosted by the same **Azure Cloud Service**?

@Royal-Philips/quality-assurance : Will seperating these two component completely introduce extra complexity? Please provide a recommendation.

**Comment by frankgoeltl** [comment]
Yes it is

 

Von: FlippieCoetser [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2015 13:08
An: Royal-Philips/iDiscover
Cc: Frank Goeltl
Betreff: Re: [iDiscover] List of Azure Services (#2)

 

is iDiscover.API and iDiscover.APP supported and hosted by the same Azure Cloud Service?

@Royal-Philips/quality-assurance <https://github.com/orgs/Royal-Philips/teams/quality-assurance>  : Will seperating these two component completely introduce extra complexity? Please provide a recommendation.

**Comment by FlippieCoetser** [comment]
As agreed in @Royal-Philips/quality-assurance Team herewith requirements for MS Azure

## Production Environment:
**Azure Active Directory** x 1
**Azure Cloud Service** x 1
**Azure SQL DB** x 1

## Quality Assurance:
**Azure Active Directory** x 1 (Reuse Production)
**Azure Cloud Service** x 1
**Azure SQL DB** x 1

## Develop Environment:
**Azure Active Directory** x 1 (Reuse Production)
**Azure Cloud Service** x 1
**Azure SQL DB** x 1
**Linux VM A1 Basic Tier** x 1
